### ISSUE TITLE
Circular call to script handler 'post-package-install' detected

### ISSUE THREAD

**Issue by riasvdv** [pixelfear/composer-dist-plugin#4] opened 2020-08-07 07:28 UTC
When using composer 2, I'm getting the following exception

![image](https://user-images.githubusercontent.com/3626559/89620614-3556e980-d890-11ea-9986-4adb169c9458.png)

It happens right after downloading the "dist", so I assume it's related to this plugin

**Comment by jasonvarga** [comment] 2020-08-07 12:13
Running the command a second time fixes it.

**Comment by jonassiewertsen** [comment] 2020-10-24 13:30
I am running into this issue as well via GitHub actions. It may be related:

<img width="865" alt="Screenshot 2020-10-24 at 15 04 55" src="https://user-images.githubusercontent.com/38906163/97083013-cdea4380-160d-11eb-825a-4199cd86c78e.png">

https://github.com/jonassiewertsen/statamic-butik/actions/runs/325922541

**Comment by duncanmcclean** [comment] 2020-10-24 20:48
Also just run into a test failing due to this. https://github.com/doublethreedigital/sc-digital-products/runs/1303127649?check_suite_focus=true

**Comment by adamseidtahir** [comment] 2020-10-26 10:37
I also just ran into this problem when attempting to upgrade to Laravel 8.

![Skärmavbild 2020-10-26 kl  11 32 17](https://user-images.githubusercontent.com/37052381/97162501-97ccd100-177f-11eb-9f27-e8a87377e636.png)

**Comment by jasonvarga** [comment] 2020-10-26 17:16
Hmm I know this was an issue (and clearly still is for others) but I can't seem to reproduce it anymore.

What version of Composer are you running?

```
composer -V
```

I'm not sure just yet on how to check that within a GitHub action (short of adding `composer -V` to your workflow).

**Comment by jesseleite** [comment] 2020-10-27 17:25
To anyone that is having this issue, can you paste your `php please support:details` output, so we can see which (if any) addons you have installed?

**Comment by jasonvarga** [comment] 2020-10-27 17:26
(Assuming you're using Statamic)

**Comment by edalzell** [comment] 2020-10-27 23:01
I have this and I can't run that command cuz Statamic didn't install properly. I have an addon that uses that `dist` plugin as well, so that bug is in that addon (mine) as well.

**Comment by jasonvarga** [comment] 2020-10-27 23:03
What about `composer -V`?

**Comment by edalzell** [comment] 2020-10-28 01:40
```
Statamic 3.0.20 Pro
Laravel 7.28.4
PHP 7.4.11
edalzell/anvil dev-main
edalzell/blade-directives dev-main
edalzell/feeds dev-main
edalzell/mailchimp dev-main
edalzell/pinboard dev-master
edalzell/rss dev-master
silentz/akismet dev-main
```

```
❯ composer -V
Composer version 2.0.2 2020-10-25 23:03:59
```

Confirmed failed the first time, worked the second time. Let me know how I can help debug this as it looks like my addons do this too.

**Comment by duncanmcclean** [comment] 2020-10-30 20:01
Ran into this issue when trying to install my addon locally as well, as it uses this plugin. If you want to replicate easilly, [clone this repo down](https://github.com/doublethreedigital/sc-starter-kit#quick-start) and try composer installing.

Here's some information:

**Statamic**
I can't run `p support:details` as it fails half way through the install process and gives up. But in the `composer install` process, it installs `v2.0.22`.

**PHP**
```
PHP 7.4.3 (cli) (built: Feb 20 2020 12:23:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**Composer**
```
Composer version 2.0.3 2020-10-28 15:50:55
```

**Comment by duncanmcclean** [comment] 2020-10-30 20:11
Ah... managed to temporarily fix it by downgrading to Composer 1 with `composer self-update --1`. Also seems to work in CI as well.

**Comment by jasonvarga** [comment] 2020-10-30 21:46
Right, it's only a Composer 2 issue.

**Comment by jonassiewertsen** [comment] 2020-10-31 12:23
That's my solution for now. 

It's a little slower, but downgrading to composer v1 is a good workaround for my pipeline as described by @damcclean:
https://github.com/jonassiewertsen/statamic-butik/commit/1162a017b2c16d1641b542734215fbbb77147a3c

**Comment by pierlon** [comment] 2020-11-13 00:35
This looks to be the same issue I was having with [civicrm/composer-downloads-plugin](https://github.com/civicrm/composer-downloads-plugin). Did some debugging and found it was a bug within Composer, so I filed an issue: https://github.com/composer/composer/issues/9463. The maintainer was quick to fix the issue so I'd expect it would be apart of the next release.

**Comment by jesseleite** [comment] 2020-11-13 13:46
Nice find @pierlon! 🎉

**Comment by edalzell** [comment] 2020-11-13 18:28
Composer was updated with this fix

**Comment by duncanmcclean** [comment] 2020-11-13 18:45
If it's fixed, I guess that means this issue can be closed?

**Comment by tao** [comment] 2020-11-25 10:57
I encountered this issue on Composer 2.0.4 but an update to 2.0.7 fixed the problem.

**Comment by edalzell** [comment] 2020-11-25 20:35
@jasonvarga you can close this.

**Comment by codedge** [comment] 2020-12-02 15:13
I am still getting this on Netlify using Statamic 3.0.31:

```
4:03:23 PM:   - Installing spatie/robots-txt (1.0.9): Extracting archive
4:03:23 PM:   - Installing spatie/crawler (5.0.2): Extracting archive
4:03:23 PM:   - Installing spatie/laravel-sitemap (5.9.0): Extracting archive
4:03:23 PM:   - Installing statamic/ssg (0.2.0): Extracting archive
4:03:24 PM:    0/135 [>---------------------------]   0%
4:03:24 PM:   10/135 [==>-------------------------]   7%
4:03:24 PM:   20/135 [====>-----------------------]  14%
4:03:25 PM:   30/135 [======>---------------------]  22%
4:03:25 PM:   40/135 [========>-------------------]  29%
4:03:25 PM:   49/135 [==========>-----------------]  36%
4:03:26 PM:   59/135 [============>---------------]  43%
4:03:26 PM:   69/135 [==============>-------------]  51%
4:03:26 PM:   78/135 [================>-----------]  57%
4:03:26 PM:   85/135 [=================>----------]  62%  - Downloading statamic/cms (dist)
4:03:33 PM:   - Installing statamic/cms (dist): Extracting archive
4:03:34 PM:  135/135 [============================] 100%
4:03:34 PM:   [RuntimeException]
4:03:34 PM:   Circular call to script handler 'post-package-install' detected
4:03:34 PM: install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
```

Composer version 2.0.7 and 2.0.8 produce this error. It seems to only happen on Netlify. Locally I am unable to reproduce this. 

Any ideas?

### Update

It works perfectly on Vercel. It is beyond me why it does not on Netlify. Does not seem a problem with this package here and/or Statamic and its addons,.

**Comment by jasonvarga** [comment] 2020-12-09 23:29
Thanks for the updates here - especially @pierlon 

I'm not sure what's up with Netlify @codedge are they definitely on the latest version of Composer? Closing this issue but feel free to open a new one if necessary.

**Closed as completed by jasonvarga** 2020-12-09 23:29 UTC
